# Generated by Django 2.0.5 on 2020-11-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('worker_position', models.TextField(blank=True, null=True, verbose_name='Занимаемая должность')),
                ('worker_age', models.CharField(max_length=3, verbose_name='Возраст')),
            ],
        ),
    ]
